#!/usr/bin/env node
/*
 * Rebuilds the accounts WASM from quantum-coin-go and regenerates:
 *   - wasmBase64.js        (base64-encoded WASM, exported via getBase64Wasm())
 *   - wasm_exec.js         (synced from the building Go toolchain's GOROOT)
 *   - EXPECTED_WASM_SHA256 (patched into index.js; build-time hash)
 *
 * The ~10MB base64 blob is generated here and must NOT be opened by hand.
 * Only the printed sha256 / sizes are meant to be read.
 *
 * Usage:
 *   node scripts/build-wasm.js            # uses ../quantum-coin-go
 *   QC_GO_DIR=/path/to/quantum-coin-go node scripts/build-wasm.js
 */
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const sdkDir = path.resolve(__dirname, '..');
const goDir = process.env.QC_GO_DIR
    ? path.resolve(process.env.QC_GO_DIR)
    : path.resolve(sdkDir, '..', 'quantum-coin-go');

function run(cmd, args, opts) {
    return execFileSync(cmd, args, { encoding: 'utf8', ...opts }).trim();
}

function main() {
    if (!fs.existsSync(goDir)) {
        throw new Error(`quantum-coin-go not found at ${goDir} (set QC_GO_DIR)`);
    }

    const goroot = run('go', ['env', 'GOROOT']);
    const wasmExecSrc = path.join(goroot, 'lib', 'wasm', 'wasm_exec.js');
    if (!fs.existsSync(wasmExecSrc)) {
        throw new Error(`wasm_exec.js not found at ${wasmExecSrc}`);
    }

    const outWasm = path.join(os.tmpdir(), `libgodp.${process.pid}.wasm`);
    console.log(`Building WASM from ${goDir} ...`);
    run('go', ['build', '-o', outWasm, './wasm/web'], {
        cwd: goDir,
        env: { ...process.env, GOOS: 'js', GOARCH: 'wasm' },
    });

    const wasmBytes = fs.readFileSync(outWasm);
    const sha256 = crypto.createHash('sha256').update(wasmBytes).digest('hex');
    const base64 = wasmBytes.toString('base64');

    // Sync the Go runtime shim so it matches the toolchain that built the WASM.
    fs.copyFileSync(wasmExecSrc, path.join(sdkDir, 'wasm_exec.js'));

    // Write wasmBase64.js (whole-file write; never hand-edited).
    const wasmBase64Js =
        '// AUTO-GENERATED by scripts/build-wasm.js - do not edit by hand.\n' +
        '// Base64-encoded quantum-coin-go accounts WASM (GOOS=js GOARCH=wasm).\n' +
        'function getBase64Wasm() {\n' +
        '    return "' + base64 + '";\n' +
        '}\n' +
        'module.exports = { getBase64Wasm };\n';
    fs.writeFileSync(path.join(sdkDir, 'wasmBase64.js'), wasmBase64Js);

    // Patch EXPECTED_WASM_SHA256 in index.js.
    const indexPath = path.join(sdkDir, 'index.js');
    let indexSrc = fs.readFileSync(indexPath, 'utf8');
    const constRe = /const EXPECTED_WASM_SHA256 = "[0-9a-fA-F]*";/;
    if (!constRe.test(indexSrc)) {
        throw new Error('Could not find EXPECTED_WASM_SHA256 constant in index.js');
    }
    indexSrc = indexSrc.replace(constRe, `const EXPECTED_WASM_SHA256 = "${sha256}";`);
    fs.writeFileSync(indexPath, indexSrc);

    fs.rmSync(outWasm, { force: true });

    console.log(`wasm bytes      : ${wasmBytes.length}`);
    console.log(`base64 length   : ${base64.length}`);
    console.log(`sha256          : ${sha256}`);
    console.log('Updated: wasmBase64.js, wasm_exec.js, index.js (EXPECTED_WASM_SHA256)');
}

main();
